package com.govtprep.app.ui.theme

import androidx.compose.runtime.*

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Bilingual string system — EN / HI
// Access via S.xxx anywhere in Compose tree
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

data class Strings(
    // ── Nav ──
    val home: String,
    val tests: String,
    val analysis: String,
    val profile: String,

    // ── Login ──
    val welcomeBack: String,
    val signInContinue: String,
    val email: String,
    val emailPlaceholder: String,
    val password: String,
    val signIn: String,
    val noAccount: String,
    val createOne: String,

    // ── Signup ──
    val createAccount: String,
    val startJourney: String,
    val fullName: String,
    val namePlaceholder: String,
    val minChars: String,
    val alreadyHaveAccount: String,
    val signInLink: String,

    // ── Home ──
    val goodMorning: String,
    val goodAfternoon: String,
    val goodEvening: String,
    val student: String,
    val startQuickTest: String,
    val resumeTest: String,
    val quickTestDesc: String,
    val resumeTestDesc: String,
    val todaysProgress: String,
    val testsToday: String,
    val studyTime: String,
    val dailyGoalReached: String,
    val moreToGoal: String, // "{n} more to hit daily goal"
    val performance: String,
    val accuracy: String,
    val avgScore: String,
    val recentTests: String,
    val dailyQuiz: String,
    val previousYearPapers: String,

    // ── Feedback ──
    val feedback: String,
    val feedbackHint: String,
    val sendFeedback: String,
    val feedbackSent: String,
    val feedbackEmpty: String,

    // ── Tests ──
    val allTests: String,
    val all: String,
    val fullTests: String,
    val subjectTests: String,
    val chapterTests: String,
    val quickTests: String,
    val noTestsAvailable: String,

    // ── Analysis ──
    val analytics: String,
    val overallStats: String,
    val totalTests: String,
    val scoreTrend: String,
    val takeMoreTests: String,
    val subjectPerformance: String,
    val noSubjectData: String,
    val mistakeReview: String,
    val noMistakes: String,
    val review: String,

    // ── Profile ──
    val target: String,
    val stats: String,
    val achievements: String,
    val streak: String,
    val highAccuracy: String,
    val tenPlusTests: String,
    val settings: String,
    val notifications: String,
    val lightMode: String,
    val language: String,
    val hindi: String,
    val editProfile: String,
    val adminPanel: String,
    val signOut: String,

    // ── Edit Profile ──
    val personalInfo: String,
    val phoneNumber: String,
    val phonePlaceholder: String,
    val saveChanges: String,
    val saving: String,
    val changePassword: String,
    val newPassword: String,
    val confirmPassword: String,
    val reEnterPassword: String,
    val updatePassword: String,
    val passwordMinError: String,
    val passwordMismatch: String,

    // ── Exam ──
    val selectSubExam: String,
    val fullMockTests: String,
    val comingSoon: String,
    val pro: String,
    val subjects: String,

    // ── Test (active, instructions, results) ──
    val loadingTest: String,
    val questions: String,
    val duration: String,
    val minutes: String,
    val totalMarks: String,
    val correctAnswer: String,
    val negativeMarking: String,
    val marks: String,
    val rules: String,
    val rule1: String,
    val rule2: String,
    val rule3: String,
    val rule4: String,
    val startTest: String,
    val question: String,
    val submit: String,
    val cancelExit: String,
    val answered: String,
    val unanswered: String,
    val marked: String,
    val submitTest: String,
    val submitTestQ: String,
    val skipped: String,
    val cancel: String,
    val scoring: String,
    val score: String,
    val excellent: String,
    val goodJob: String,
    val keepPracticing: String,
    val needMorePractice: String,
    val correct: String,
    val incorrect: String,
    val unattempted: String,
    val timeTaken: String,
    val reviewAnswers: String,
    val goBack: String,
    val explanation: String,
    val correctLabel: String,
    val wrongLabel: String,
    val skippedLabel: String,

    // ── Splash ──
    val tagline: String,
)

val EN = Strings(
    home = "Home", tests = "Tests", analysis = "Analysis", profile = "Profile",
    welcomeBack = "Welcome Back", signInContinue = "Sign in to continue your preparation",
    email = "EMAIL", emailPlaceholder = "your@email.com", password = "PASSWORD",
    signIn = "Sign In", noAccount = "Don't have an account?  ", createOne = "Create one",
    createAccount = "Create Account", startJourney = "Start your exam preparation journey",
    fullName = "FULL NAME", namePlaceholder = "Your full name", minChars = "Min 6 characters",
    alreadyHaveAccount = "Already have an account?  ", signInLink = "Sign in",
    goodMorning = "Good morning", goodAfternoon = "Good afternoon", goodEvening = "Good evening",
    student = "Student", startQuickTest = "Start Quick Test", resumeTest = "Resume Test",
    quickTestDesc = "Jump into a 25-question challenge", resumeTestDesc = "You have an unfinished test",
    todaysProgress = "TODAY'S PROGRESS", testsToday = "Tests today", studyTime = "Study time",
    dailyGoalReached = "Daily goal reached!", moreToGoal = "more to hit daily goal",
    performance = "PERFORMANCE", accuracy = "Accuracy", avgScore = "Avg Score",
    recentTests = "Recent Tests",
    dailyQuiz = "Daily Quiz",
    previousYearPapers = "PYQ Papers",
    feedback = "Feedback",
    feedbackHint = "Share your ideas or suggestions...",
    sendFeedback = "Send Feedback",
    feedbackSent = "Thank you for your feedback!",
    feedbackEmpty = "Please write something first",
    allTests = "All Tests", all = "All", fullTests = "Full Tests", subjectTests = "Subject Tests",
    chapterTests = "Chapter Tests", quickTests = "Quick Tests", noTestsAvailable = "No tests available",
    analytics = "Analytics", overallStats = "OVERALL STATS", totalTests = "Total Tests",
    scoreTrend = "SCORE TREND", takeMoreTests = "Take more tests to see trends",
    subjectPerformance = "SUBJECT PERFORMANCE", noSubjectData = "No subject data yet",
    mistakeReview = "Mistake Review", noMistakes = "No mistakes to review yet", review = "Review",
    target = "Target", stats = "STATS", achievements = "ACHIEVEMENTS",
    streak = "Streak", highAccuracy = "High Accuracy", tenPlusTests = "10+ Tests",
    settings = "SETTINGS", notifications = "Notifications", lightMode = "Enable Light Mode",
    language = "Language", hindi = "हिन्दी",
    editProfile = "Edit Profile", adminPanel = "Admin Panel", signOut = "Sign Out",
    personalInfo = "PERSONAL INFO", phoneNumber = "Phone Number", phonePlaceholder = "Enter phone number",
    saveChanges = "Save Changes", saving = "Saving...", changePassword = "CHANGE PASSWORD",
    newPassword = "New Password", confirmPassword = "Confirm Password", reEnterPassword = "Re-enter password",
    updatePassword = "Update Password",
    passwordMinError = "Password must be at least 6 characters", passwordMismatch = "Passwords don't match",
    selectSubExam = "Select Sub-Exam", fullMockTests = "Full Mock Tests",
    comingSoon = "COMING SOON", pro = "PRO", subjects = "subjects",
    loadingTest = "Loading test...", questions = "Questions", duration = "Duration",
    minutes = "minutes", totalMarks = "Total Marks", correctAnswer = "Correct Answer",
    negativeMarking = "Negative Marking", marks = "marks", rules = "RULES",
    rule1 = "Each question has only one correct answer", rule2 = "You can mark questions for review",
    rule3 = "Timer starts once you begin", rule4 = "Test auto-submits when time expires",
    startTest = "Start Test", question = "Question", submit = "Submit", cancelExit = "Cancel & Exit",
    answered = "Answered", unanswered = "Unanswered", marked = "Marked",
    submitTest = "Submit Test", submitTestQ = "Submit Test?", skipped = "Skipped", cancel = "Cancel",
    scoring = "Scoring your answers...", score = "Score",
    excellent = "Excellent Performance!", goodJob = "Good Job!",
    keepPracticing = "Keep Practicing!", needMorePractice = "Need More Practice",
    correct = "Correct", incorrect = "Incorrect", unattempted = "Unattempted", timeTaken = "Time Taken",
    reviewAnswers = "Review Answers", goBack = "Go Back", explanation = "EXPLANATION",
    correctLabel = "CORRECT", wrongLabel = "WRONG", skippedLabel = "SKIPPED",
    tagline = "Learn it like a pro",
)

val HI = Strings(
    home = "होम", tests = "टेस्ट", analysis = "विश्लेषण", profile = "प्रोफ़ाइल",
    welcomeBack = "वापसी पर स्वागत", signInContinue = "अपनी तैयारी जारी रखने के लिए लॉगिन करें",
    email = "ईमेल", emailPlaceholder = "your@email.com", password = "पासवर्ड",
    signIn = "लॉगिन करें", noAccount = "खाता नहीं है?  ", createOne = "बनाएं",
    createAccount = "खाता बनाएं", startJourney = "अपनी परीक्षा की तैयारी शुरू करें",
    fullName = "पूरा नाम", namePlaceholder = "अपना नाम लिखें", minChars = "कम से कम 6 अक्षर",
    alreadyHaveAccount = "पहले से खाता है?  ", signInLink = "लॉगिन करें",
    goodMorning = "सुप्रभात", goodAfternoon = "नमस्कार", goodEvening = "शुभ संध्या",
    student = "छात्र", startQuickTest = "क्विक टेस्ट शुरू करें", resumeTest = "टेस्ट जारी रखें",
    quickTestDesc = "25 प्रश्नों की चुनौती शुरू करें", resumeTestDesc = "आपका एक टेस्ट अधूरा है",
    todaysProgress = "आज की प्रगति", testsToday = "आज के टेस्ट", studyTime = "पढ़ाई का समय",
    dailyGoalReached = "दैनिक लक्ष्य पूरा!", moreToGoal = "और टेस्ट दैनिक लक्ष्य के लिए",
    performance = "प्रदर्शन", accuracy = "सटीकता", avgScore = "औसत स्कोर",
    recentTests = "हाल के टेस्ट",
    dailyQuiz = "दैनिक क्विज़",
    previousYearPapers = "पिछले वर्ष के प्रश्न",
    feedback = "प्रतिक्रिया",
    feedbackHint = "अपने विचार या सुझाव साझा करें...",
    sendFeedback = "प्रतिक्रिया भेजें",
    feedbackSent = "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    feedbackEmpty = "कृपया पहले कुछ लिखें",
    allTests = "सभी टेस्ट", all = "सभी", fullTests = "पूर्ण टेस्ट", subjectTests = "विषय टेस्ट",
    chapterTests = "अध्याय टेस्ट", quickTests = "क्विक टेस्ट", noTestsAvailable = "कोई टेस्ट उपलब्ध नहीं",
    analytics = "विश्लेषण", overallStats = "समग्र आंकड़े", totalTests = "कुल टेस्ट",
    scoreTrend = "स्कोर रुझान", takeMoreTests = "रुझान देखने के लिए और टेस्ट दें",
    subjectPerformance = "विषय प्रदर्शन", noSubjectData = "अभी कोई विषय डेटा नहीं",
    mistakeReview = "गलतियों की समीक्षा", noMistakes = "अभी कोई गलती समीक्षा नहीं", review = "समीक्षा",
    target = "लक्ष्य", stats = "आंकड़े", achievements = "उपलब्धियां",
    streak = "स्ट्रीक", highAccuracy = "उच्च सटीकता", tenPlusTests = "10+ टेस्ट",
    settings = "सेटिंग्स", notifications = "सूचनाएं", lightMode = "लाइट मोड चालू करें",
    language = "भाषा", hindi = "हिन्दी",
    editProfile = "प्रोफ़ाइल संपादित करें", adminPanel = "एडमिन पैनल", signOut = "लॉगआउट",
    personalInfo = "व्यक्तिगत जानकारी", phoneNumber = "फ़ोन नंबर", phonePlaceholder = "फ़ोन नंबर दर्ज करें",
    saveChanges = "बदलाव सहेजें", saving = "सहेजा जा रहा है...", changePassword = "पासवर्ड बदलें",
    newPassword = "नया पासवर्ड", confirmPassword = "पासवर्ड पुष्टि", reEnterPassword = "पासवर्ड दोबारा लिखें",
    updatePassword = "पासवर्ड अपडेट करें",
    passwordMinError = "पासवर्ड कम से कम 6 अक्षर का होना चाहिए", passwordMismatch = "पासवर्ड मेल नहीं खाते",
    selectSubExam = "उप-परीक्षा चुनें", fullMockTests = "पूर्ण मॉक टेस्ट",
    comingSoon = "जल्द आ रहा है", pro = "PRO", subjects = "विषय",
    loadingTest = "टेस्ट लोड हो रहा है...", questions = "प्रश्न", duration = "अवधि",
    minutes = "मिनट", totalMarks = "कुल अंक", correctAnswer = "सही उत्तर",
    negativeMarking = "नकारात्मक अंकन", marks = "अंक", rules = "नियम",
    rule1 = "प्रत्येक प्रश्न का केवल एक सही उत्तर है", rule2 = "आप प्रश्नों को समीक्षा के लिए चिह्नित कर सकते हैं",
    rule3 = "शुरू करते ही टाइमर चालू हो जाएगा", rule4 = "समय समाप्त होने पर टेस्ट स्वतः सबमिट हो जाएगा",
    startTest = "टेस्ट शुरू करें", question = "प्रश्न", submit = "जमा करें", cancelExit = "रद्द करें और बाहर निकलें",
    answered = "उत्तर दिए", unanswered = "अनुत्तरित", marked = "चिह्नित",
    submitTest = "टेस्ट जमा करें", submitTestQ = "टेस्ट जमा करें?", skipped = "छोड़े गए", cancel = "रद्द करें",
    scoring = "आपके उत्तर जांचे जा रहे हैं...", score = "स्कोर",
    excellent = "शानदार प्रदर्शन!", goodJob = "बहुत अच्छे!",
    keepPracticing = "अभ्यास जारी रखें!", needMorePractice = "और अभ्यास की ज़रूरत",
    correct = "सही", incorrect = "गलत", unattempted = "नहीं किए", timeTaken = "लगा समय",
    reviewAnswers = "उत्तर समीक्षा", goBack = "वापस जाएं", explanation = "व्याख्या",
    correctLabel = "सही", wrongLabel = "गलत", skippedLabel = "छोड़ा",
    tagline = "पढ़ो तो प्रो की तरह",
)

val LocalStrings = staticCompositionLocalOf { EN }

// Global accessor — use S.home, S.signIn, etc.
val S: Strings
    @Composable @ReadOnlyComposable
    get() = LocalStrings.current
